In [140]:
from IPython.utils.py3compat import decode
import pandas as pd
data=pd.read_csv('consumo_adinelsa_202305_0.csv',encoding='latin-1',delimiter=';')
count1 = data['TARIFA'].value_counts().get("BT5B", 0)
count2 = data['TARIFA'].value_counts().get("BT4", 0)
count3 = data['TARIFA'].value_counts().get("BT5A", 0)
count4 = data['TARIFA'].value_counts().get("BT5D", 0)
count5 = data['TARIFA'].value_counts().get("BT6", 0)
count6 = data['TARIFA'].value_counts().get("BT8", 0)
count7 = data['TARIFA'].value_counts().get("MT2", 0)
count8 = data['TARIFA'].value_counts().get("MT3", 0)
count9 = data['TARIFA'].value_counts().get("MT4", 0)

print(f"El número de registros de tipo 'A' es: {count1}\n{count2}\n{count3}\n{count4}\n{count5}\n{count6}\n{count7}\n{count8}\n{count9} ")

El número de registros de tipo 'A' es: 67091
1
1
2
105
10369
14
8
39

In [117]:
data.head()

,FECHA_CORTE,PERIODO_FACTURACION,UUID,UBIGEO,DEPARTAMENTO,PROVINCIA,DISTRITO,LOCALIDAD,TARIFA,FECHA_INICIO,CONSUMO_KW,POTENCIA_CONTRATADA,MONTO_SOLES,FASE,CODIGO_CIU
0,20230608,202305,C201904291019902323190424,151025,LIMA,YAUYOS,QUINOCAY,QUINOCAY,BT5B,20190429,6.0,3.0,7.5,MONOFASICO,T9700
1,20230608,202305,C201908191019904549190815,151017,LIMA,YAUYOS,HUA¥EC,HUAÑEC,BT5B,20190819,0.0,3.0,6.2,MONOFASICO,T9700
2,20230608,202305,C201909281019904871190917,151029,LIMA,YAUYOS,TAURIPAMPA,TAURIPAMPA,BT5B,20190928,1.0,3.0,6.4,MONOFASICO,T9700
3,20230608,202305,C202002061019906396200203,151022,LIMA,YAUYOS,OMAS,ESQUINA DE OMAS,BT5B,20200206,44.0,3.0,34.2,MONOFASICO,T9700
4,20230608,202305,C202011060199085730201106,151017,LIMA,YAUYOS,HUA¥EC,HUA¥EC,BT5B,20201106,0.0,3.0,6.2,MONOFASICO,T9700

In [118]:
print (data.isnull().sum())

FECHA_CORTE            0
PERIODO_FACTURACION    0
UUID                   0
UBIGEO                 0
DEPARTAMENTO           0
PROVINCIA              0
DISTRITO               0
LOCALIDAD              0
TARIFA                 0
FECHA_INICIO           0
CONSUMO_KW             0
POTENCIA_CONTRATADA    0
MONTO_SOLES            0
FASE                   0
CODIGO_CIU             0
dtype: int64

In [141]:
data.reset_index()
data.head(900)

,FECHA_CORTE,PERIODO_FACTURACION,UUID,UBIGEO,DEPARTAMENTO,PROVINCIA,DISTRITO,LOCALIDAD,TARIFA,FECHA_INICIO,CONSUMO_KW,POTENCIA_CONTRATADA,MONTO_SOLES,FASE,CODIGO_CIU
0,20230608,202305,C201904291019902323190424,151025,LIMA,YAUYOS,QUINOCAY,QUINOCAY,BT5B,20190429,6.0,3.0,7.5,MONOFASICO,T9700
1,20230608,202305,C201908191019904549190815,151017,LIMA,YAUYOS,HUA¥EC,HUAÑEC,BT5B,20190819,0.0,3.0,6.2,MONOFASICO,T9700
2,20230608,202305,C201909281019904871190917,151029,LIMA,YAUYOS,TAURIPAMPA,TAURIPAMPA,BT5B,20190928,1.0,3.0,6.4,MONOFASICO,T9700
3,20230608,202305,C202002061019906396200203,151022,LIMA,YAUYOS,OMAS,ESQUINA DE OMAS,BT5B,20200206,44.0,3.0,34.2,MONOFASICO,T9700
4,20230608,202305,C202011060199085730201106,151017,LIMA,YAUYOS,HUA¥EC,HUA¥EC,BT5B,20201106,0.0,3.0,6.2,MONOFASICO,T9700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,20230608,202305,C201504282391171465180828,50705,AYACUCHO,PARINACOCHAS,PULLO,RELAVE,BT5B,20150428,74.0,1.0,135.0,MONOFASICO,T9700
896,20230608,202305,C201504282391171467180828,50705,AYACUCHO,PARINACOCHAS,PULLO,RELAVE,BT5B,20150428,118.0,1.0,94.8,MONOFASICO,T9700
897,20230608,202305,C201410312391171680180828,50705,AYACUCHO,PARINACOCHAS,PULLO,RELAVE,BT5B,20141031,215.0,1.0,501.2,MONOFASICO,T9700
898,20230608,202305,C201410312391172130180828,50705,AYACUCHO,PARINACOCHAS,PULLO,RELAVE,BT5B,20141031,224.0,1.0,261.2,MONOFASICO,T9700
899,20230608,202305,C201410312391172150180828,50705,AYACUCHO,PARINACOCHAS,PULLO,RELAVE,BT5B,20141031,23.0,1.0,44.8,MONOFASICO,T9700

In [120]:
print (data.dtypes)

FECHA_CORTE              int64
PERIODO_FACTURACION      int64
UUID                    object
UBIGEO                   int64
DEPARTAMENTO            object
PROVINCIA               object
DISTRITO                object
LOCALIDAD               object
TARIFA                  object
FECHA_INICIO             int64
CONSUMO_KW             float64
POTENCIA_CONTRATADA    float64
MONTO_SOLES            float64
FASE                    object
CODIGO_CIU              object
dtype: object

In [121]:
data["UUID"] = data["UUID"].astype('category')
data["DEPARTAMENTO"] = data["DEPARTAMENTO"].astype('category')
data["PROVINCIA"] = data["PROVINCIA"].astype('category')
data["DISTRITO"] = data["DISTRITO"].astype('category')
data["LOCALIDAD"] = data["LOCALIDAD"].astype('category')
data["TARIFA"] = data["TARIFA"].astype('category')
data["FASE"] = data["FASE"].astype('category')
data["CODIGO_CIU"] = data["CODIGO_CIU"].astype('category')
print (data.dtypes)

FECHA_CORTE               int64
PERIODO_FACTURACION       int64
UUID                   category
UBIGEO                    int64
DEPARTAMENTO           category
PROVINCIA              category
DISTRITO               category
LOCALIDAD              category
TARIFA                 category
FECHA_INICIO              int64
CONSUMO_KW              float64
POTENCIA_CONTRATADA     float64
MONTO_SOLES             float64
FASE                   category
CODIGO_CIU             category
dtype: object

In [122]:
categorical_data=data.drop(['FECHA_CORTE','PERIODO_FACTURACION','UBIGEO','FECHA_INICIO','CONSUMO_KW','POTENCIA_CONTRATADA','MONTO_SOLES'],axis=1)
categorical_data.head()

,UUID,DEPARTAMENTO,PROVINCIA,DISTRITO,LOCALIDAD,TARIFA,FASE,CODIGO_CIU
0,C201904291019902323190424,LIMA,YAUYOS,QUINOCAY,QUINOCAY,BT5B,MONOFASICO,T9700
1,C201908191019904549190815,LIMA,YAUYOS,HUA¥EC,HUAÑEC,BT5B,MONOFASICO,T9700
2,C201909281019904871190917,LIMA,YAUYOS,TAURIPAMPA,TAURIPAMPA,BT5B,MONOFASICO,T9700
3,C202002061019906396200203,LIMA,YAUYOS,OMAS,ESQUINA DE OMAS,BT5B,MONOFASICO,T9700
4,C202011060199085730201106,LIMA,YAUYOS,HUA¥EC,HUA¥EC,BT5B,MONOFASICO,T9700

In [123]:
print(categorical_data.dtypes)

UUID            category
DEPARTAMENTO    category
PROVINCIA       category
DISTRITO        category
LOCALIDAD       category
TARIFA          category
FASE            category
CODIGO_CIU      category
dtype: object

In [ ]:
#LABEL ENCODING
categorical_data ["UUID"]=categorical_data["UUID"].cat.codes
#categorical_data ["DEPARTAMENTO"]=categorical_data["DEPARTAMENTO"].cat.codes
#categorical_data ["PROVINCIA"]=categorical_data["PROVINCIA"].cat.codes
#categorical_data ["DISTRITO"]=categorical_data["DISTRITO"].cat.codes
#categorical_data ["LOCALIDAD"]=categorical_data["LOCALIDAD"].cat.codes
#categorical_data ["TARIFA"]=categorical_data["TARIFA"].cat.codes
#categorical_data ["FASE"]=categorical_data["FASE"].cat.codes
#categorical_data ["CODIGO_CIU"]=categorical_data["CODIGO_CIU"].cat.codes
#categorical_data

In [125]:
numerical_data=data.drop(['UUID','DEPARTAMENTO','PROVINCIA','DISTRITO','LOCALIDAD','TARIFA','FASE','CODIGO_CIU'],axis=1)
numerical_data.head()

,FECHA_CORTE,PERIODO_FACTURACION,UBIGEO,FECHA_INICIO,CONSUMO_KW,POTENCIA_CONTRATADA,MONTO_SOLES
0,20230608,202305,151025,20190429,6.0,3.0,7.5
1,20230608,202305,151017,20190819,0.0,3.0,6.2
2,20230608,202305,151029,20190928,1.0,3.0,6.4
3,20230608,202305,151022,20200206,44.0,3.0,34.2
4,20230608,202305,151017,20201106,0.0,3.0,6.2

In [126]:
new_data=categorical_data.join(numerical_data)
new_data.head()

,UUID,DEPARTAMENTO,PROVINCIA,DISTRITO,LOCALIDAD,TARIFA,FASE,CODIGO_CIU,FECHA_CORTE,PERIODO_FACTURACION,UBIGEO,FECHA_INICIO,CONSUMO_KW,POTENCIA_CONTRATADA,MONTO_SOLES
0,62823,LIMA,YAUYOS,QUINOCAY,1455,2,0,78,20230608,202305,151025,20190429,6.0,3.0,7.5
1,64059,LIMA,YAUYOS,HUA¥EC,798,2,0,78,20230608,202305,151017,20190819,0.0,3.0,6.2
2,64341,LIMA,YAUYOS,TAURIPAMPA,1811,2,0,78,20230608,202305,151029,20190928,1.0,3.0,6.4
3,65535,LIMA,YAUYOS,OMAS,646,2,0,78,20230608,202305,151022,20200206,44.0,3.0,34.2
4,67802,LIMA,YAUYOS,HUA¥EC,797,2,0,78,20230608,202305,151017,20201106,0.0,3.0,6.2

In [137]:
encoded_dep= pd.get_dummies(categorical_data['DEPARTAMENTO'], prefix='DEPARTAMENTO')
encoded_prov= pd.get_dummies(categorical_data['PROVINCIA'], prefix='PROVINCIA')
encoded_dist= pd.get_dummies(categorical_data['DISTRITO'], prefix='DISTRITO')
encoded_local= pd.get_dummies(categorical_data['LOCALIDAD'], prefix='LOCALIDAD')
encoded_tarif= pd.get_dummies(categorical_data['TARIFA'], prefix='TARIFA')
encoded_fase= pd.get_dummies(categorical_data['FASE'], prefix='FASE')
encoded_codigo_ciu= pd.get_dummies(categorical_data['CODIGO_CIU'], prefix='CODIGO_CIU')
hot_cat_data1=categorical_data.join(encoded_dist)
hot_cat_data2=hot_cat_data1.join(encoded_prov)
hot_cat_data3=hot_cat_data2.join(encoded_dep)
hot_cat_data4=hot_cat_data3.join(encoded_local)
hot_cat_data5=hot_cat_data4.join(encoded_tarif)
hot_cat_data6=hot_cat_data5.join(encoded_fase)
hot_cat_data_fin=hot_cat_data6.join(encoded_codigo_ciu)

columna_dep = new_data['DEPARTAMENTO']
valores_unicos = columna_dep.unique()
print(valores_unicos)

['LIMA', 'AYACUCHO', 'AREQUIPA', 'HUANCAVELICA', 'CAJAMARCA', ..., 'ICA', 'AMAZONAS', 'APURIMAC', 'UCAYALI', 'JUNIN']
Length: 13
Categories (13, object): ['AMAZONAS', 'ANCASH', 'APURIMAC', 'AREQUIPA', ..., 'LIMA', 'LORETO', 'PASCO', 'UCAYALI']

In [143]:
hot_cat_data_fin.head(5)

,UUID,DEPARTAMENTO,PROVINCIA,DISTRITO,LOCALIDAD,TARIFA,FASE,CODIGO_CIU,DISTRITO_ACOCRO,DISTRITO_ACOS VINCHOS,...,CODIGO_CIU_70,CODIGO_CIU_71,CODIGO_CIU_72,CODIGO_CIU_73,CODIGO_CIU_74,CODIGO_CIU_75,CODIGO_CIU_76,CODIGO_CIU_77,CODIGO_CIU_78,CODIGO_CIU_79
0,62823,LIMA,YAUYOS,QUINOCAY,1455,2,0,78,False,False,...,False,False,False,False,False,False,False,False,True,False
1,64059,LIMA,YAUYOS,HUA¥EC,798,2,0,78,False,False,...,False,False,False,False,False,False,False,False,True,False
2,64341,LIMA,YAUYOS,TAURIPAMPA,1811,2,0,78,False,False,...,False,False,False,False,False,False,False,False,True,False
3,65535,LIMA,YAUYOS,OMAS,646,2,0,78,False,False,...,False,False,False,False,False,False,False,False,True,False
4,67802,LIMA,YAUYOS,HUA¥EC,797,2,0,78,False,False,...,False,False,False,False,False,False,False,False,True,False

In [ ]:
print(new_data.dtypes)

UUID                      int32
DEPARTAMENTO           category
PROVINCIA              category
DISTRITO               category
LOCALIDAD                 int16
TARIFA                     int8
FASE                       int8
CODIGO_CIU                 int8
FECHA_CORTE               int64
PERIODO_FACTURACION       int64
UBIGEO                    int64
FECHA_INICIO              int64
CONSUMO_KW              float64
POTENCIA_CONTRATADA     float64
MONTO_SOLES             float64
dtype: object

In [ ]:
new_data.head(6)

,UUID,DEPARTAMENTO,PROVINCIA,DISTRITO,LOCALIDAD,TARIFA,FASE,CODIGO_CIU,FECHA_CORTE,PERIODO_FACTURACION,UBIGEO,FECHA_INICIO,CONSUMO_KW,POTENCIA_CONTRATADA,MONTO_SOLES
0,62823,LIMA,YAUYOS,QUINOCAY,1455,2,0,78,20230608,202305,151025,20190429,6.0,3.0,7.5
1,64059,LIMA,YAUYOS,HUA¥EC,798,2,0,78,20230608,202305,151017,20190819,0.0,3.0,6.2
2,64341,LIMA,YAUYOS,TAURIPAMPA,1811,2,0,78,20230608,202305,151029,20190928,1.0,3.0,6.4
3,65535,LIMA,YAUYOS,OMAS,646,2,0,78,20230608,202305,151022,20200206,44.0,3.0,34.2
4,67802,LIMA,YAUYOS,HUA¥EC,797,2,0,78,20230608,202305,151017,20201106,0.0,3.0,6.2
5,73115,LIMA,YAUYOS,OMAS,1789,2,0,78,20230608,202305,151022,20220606,1.0,3.0,6.3

In [ ]:
numerical_data['MONTO_SOLES']=numerical_data['MONTO_SOLES'].astype("category")
numerical_data['MONTO_SOLES']=numerical_data['MONTO_SOLES'].cat.codes
pot_contr=numerical_data.groupby('POTENCIA_CONTRATADA')['MONTO_SOLES'].mean()
pot_contr
#ver como se puede hacer el categorical para un tipo de dato numerico

POTENCIA_CONTRATADA
0.01       177.333333
0.06        98.000000
0.09       128.000000
0.11       284.833333
0.12       296.000000
             ...
150.00    4770.000000
160.00    5788.000000
170.00    5711.000000
200.00    5786.000000
300.00    5791.000000
Name: MONTO_SOLES, Length: 349, dtype: float64

In [ ]:
print(numerical_data.dtypes)

FECHA_CORTE              int64
PERIODO_FACTURACION      int64
UBIGEO                   int64
FECHA_INICIO             int64
CONSUMO_KW             float64
POTENCIA_CONTRATADA    float64
MONTO_SOLES              int16
dtype: object

In [ ]:
columna_numeros = new_data['POTENCIA_CONTRATADA']
valores_unicos = columna_numeros.unique()
print(valores_unicos)

[3.000e+00 1.000e+00 9.000e+00 2.810e+00 2.500e+00 5.000e+00 2.940e+00
 1.100e-01 1.500e-01 1.600e-01 7.000e+00 5.000e-01 9.600e-01 4.800e-01
 8.500e+01 1.200e+02 1.000e+01 9.500e-01 5.200e-01 2.000e+00 1.750e+00
 1.960e+00 5.000e+01 7.000e+01 6.000e+00 6.200e-01 6.300e-01 1.800e+00
 3.010e+00 1.000e+02 2.860e+00 4.920e+00 1.950e+00 1.230e+00 8.000e+00
 9.300e-01 1.360e+00 1.700e+00 2.040e+00 2.010e+00 7.070e+00 8.500e-01
 8.300e-01 3.000e-01 2.800e-01 4.000e+00 1.930e+00 1.800e-01 1.970e+00
 1.990e+00 1.560e+00 1.500e+00 2.120e+00 9.200e-01 2.020e+00 7.300e-01
 1.880e+00 8.020e+00 4.500e-01 4.850e+00 1.500e+01 9.000e-01 2.720e+00
 4.400e-01 2.800e+00 2.400e+00 2.960e+00 7.800e-01 5.730e+00 1.350e+00
 9.000e-02 5.300e-01 5.710e+00 1.580e+00 1.860e+00 6.610e+00 2.550e+00
 3.300e-01 1.700e-01 2.360e+00 2.000e-01 1.200e+01 1.070e+01 2.460e+00
 6.540e+00 8.680e+00 3.020e+00 1.920e+00 4.600e-01 1.020e+00 8.080e+00
 2.680e+00 2.070e+00 8.800e-01 9.900e+00 3.700e-01 8.600e-01 8.200e-01
 3.540e+00 8.900e-01 2.320e+00 3.430e+00 4.720e+00 3.360e+00 5.760e+00
 5.020e+00 8.100e-01 6.000e-02 4.010e+00 2.100e-01 3.270e+00 9.040e+00
 1.260e+01 5.750e+00 1.400e-01 9.100e-01 1.890e+00 3.980e+00 1.610e+00
 6.000e-01 7.900e-01 1.980e+00 3.040e+00 2.830e+00 3.060e+00 2.260e+00
 2.300e-01 2.150e+00 3.180e+00 2.660e+00 1.440e+00 2.730e+00 4.470e+00
 1.480e+00 1.030e+01 1.100e+00 2.100e+00 1.000e-02 3.570e+00 5.260e+00
 4.960e+00 2.080e+00 2.500e-01 4.900e-01 2.300e+00 1.270e+00 5.060e+00
 1.650e+00 6.620e+00 1.120e+00 2.050e+00 1.050e+00 6.370e+00 3.050e+00
 2.490e+00 6.490e+00 1.300e+00 7.500e+00 1.400e+01 5.200e+00 1.280e+00
 1.830e+00 1.590e+00 4.350e+00 1.210e+00 1.940e+00 8.000e-01 1.620e+00
 1.690e+00 1.910e+00 6.050e+00 4.910e+00 1.640e+00 5.500e-01 5.550e+00
 7.650e+00 4.500e+00 2.250e+00 3.840e+00 5.040e+00 6.800e-01 7.220e+00
 1.490e+00 5.100e-01 5.810e+00 1.320e+00 1.190e+00 3.510e+00 2.890e+00
 5.900e-01 8.700e-01 5.600e-01 2.230e+00 2.060e+00 4.040e+00 4.390e+00
 3.320e+00 1.070e+00 5.700e-01 1.820e+00 7.460e+00 4.060e+00 5.570e+00
 1.460e+00 6.900e+00 6.400e-01 1.090e+00 3.400e+00 1.140e+00 2.200e-01
 2.740e+00 1.420e+00 1.030e+00 1.080e+00 3.030e+00 1.850e+00 2.000e+01
 6.500e+01 1.700e+02 8.200e+01 1.500e+02 3.000e+02 2.000e+02 1.600e+02
 3.750e+00 1.300e+02 3.009e+01 2.500e+01 2.620e+00 1.170e+00 1.900e+01
 2.390e+00 2.950e+00 2.930e+00 2.650e+00 1.300e-01 5.400e-01 3.130e+00
 4.300e-01 1.340e+00 3.760e+00 3.860e+00 2.410e+00 6.500e-01 9.800e-01
 4.100e+00 1.710e+00 1.600e+00 7.330e+00 5.270e+00 4.140e+00 2.450e+00
 1.400e+00 3.380e+00 6.350e+00 2.370e+00 3.150e+00 1.510e+00 6.580e+00
 4.360e+00 1.720e+00 1.200e+00 3.480e+00 4.750e+00 9.420e+00 7.800e+00
 2.640e+00 2.670e+00 1.150e+00 3.110e+00 2.880e+00 4.510e+00 1.330e+00
 9.900e-01 2.570e+00 4.260e+00 1.730e+00 3.930e+00 4.700e-01 2.440e+00
 1.660e+00 8.410e+00 2.330e+00 7.960e+00 2.220e+00 3.340e+00 1.390e+00
 1.800e+01 4.000e+01 4.250e+01 2.990e+00 3.190e+00 7.810e+00 2.350e+00
 3.990e+00 4.430e+00 3.350e+00 1.470e+00 1.310e+00 2.600e+00 7.400e-01
 3.260e+00 6.700e-01 2.610e+00 2.910e+00 6.080e+00 2.580e+00 1.200e-01
 9.400e-01 5.560e+00 4.370e+00 1.840e+00 2.480e+00 1.630e+00 2.420e+00
 4.310e+00 2.710e+00 7.680e+00 3.650e+00 7.320e+00 2.590e+00 3.640e+00
 4.420e+00 3.160e+00 4.340e+00 1.110e+00 1.300e+01 6.980e+00 5.800e-01
 5.240e+00 1.240e+00 1.540e+00 3.630e+00 9.700e-01 7.500e-01 4.820e+00
 3.410e+00 2.980e+00 2.290e+00 2.430e+00 3.820e+00 5.300e+00 4.450e+00
 2.180e+00 6.920e+00 7.100e-01 3.600e-01 5.450e+00 9.830e+00]